### ISSUE TITLE
php-mode not enabled when tag have options

### ISSUE THREAD

**Issue by jcubic** [fred-o/jekyll-modes#3]
I'm using this code:

```
{% highlight php startinline=true %}

{% endhighlight %}
```

So I don't need to specify the `<?php` tag, but this make jekyll-modes not enable php-mode

**Comment by fred-o** [comment]
Thank you for your report. Unfortunately I don't have the capacity to maintain this project and it looks very unlikely that I will pick this up in the future. Sorry,.
