### ISSUE TITLE
Polymode rewritten. 

### ISSUE THREAD

**Issue by vspinu** [fred-o/jekyll-modes#4]
Polymode has been rewritten with many fixes and much simplified developer API. 

I would be more than happy to provide a PR, but I would need a few comprehensive examples with liquid tags for the sake of indentation. Particularly the if-else blocks in html and markdown.  

Would you be interested?

**Comment by fred-o** [comment]
Thank you for your report. Unfortunately I don't have the capacity to maintain this project and it looks very unlikely that I will pick this up in the future. Sorry,.
