### ISSUE TITLE
Don't work from Melpa

### ISSUE THREAD

**Issue by jcubic** [fred-o/jekyll-modes#5]
After polymode update the pacakge don't work anymore when you installit from Melpa.

First missing jekyll-markdown then this:

````
Debugger entered--Lisp error: (void-function pm-hbtchunkmode)
  (pm-hbtchunkmode "yaml" :mode 'yaml-mode :head-reg "\\`---\n" :tail-reg "[^\\`]---\n")
  eval((pm-hbtchunkmode "yaml" :mode 'yaml-mode :head-reg "\\`---\n" :tail-reg "[^\\`]---\n"))
```
pm is probably polymode function that was removed.

**Comment by fred-o** [comment]
Thank you for your report. Unfortunately I don't have the capacity to maintain this project and it looks very unlikely that I will pick this up in the future. Sorry,.

**Comment by jcubic** [comment]
Hmm, then maybe don't close the issue and leave it open. Or maybe you can roll back old code if you don't want to work on this. So there is no broken code that is published.

**Comment by jcubic** [comment]
I understand that you don't want to work on this project anymore, but leaving it broken is kind of uncool. The code was working in the previous version. I'm not sure how much it will take to publish to Melpa, I never did this myself.

Do you think that you can do just one more thing and publish the old version?
I'm not an expert on how Emacs packages work so I'm not sure if you can install an older version without you publishing it again.

**Comment by fred-o** [comment]
I don't think it's that easy, alas. It seems polymode has been rewritten, which breaks jekyll-modes. But jekyll-modes has the same Package-Requires that it always had (`Package-Requires: ((polymode "0.2"))`), and I don't know if there's anything else I can do to lock it against an older version of polymode.
